import { type ReactElement } from "react";
import { Badge, Button, Card } from "../design-system";
import type { PageId, TempleRole } from "../layout/nav";

const money = (n: number): string => `฿${n.toLocaleString("th-TH")}`;

function PageHead({ eyebrow, title, desc, actions }: { eyebrow: string; title: string; desc: string; actions?: ReactElement }): ReactElement {
  return (
    <div className="page-head">
      <div>
        <div className="eyebrow">{eyebrow}</div>
        <h1>{title}</h1>
        <p className="desc">{desc}</p>
      </div>
      {actions ? <div className="head-actions">{actions}</div> : null}
    </div>
  );
}

function KPI({ label, value, tone, foot }: { label: string; value: string; tone?: string; foot?: string }): ReactElement {
  return (
    <div className="kpi">
      <div className="k-label">{label}</div>
      <div className="k-value tnum" style={tone ? { color: `var(--${tone})` } : undefined}>{value}</div>
      {foot ? <div className="k-foot">{foot}</div> : null}
    </div>
  );
}

function Table({ children }: { children: ReactElement | ReactElement[] }): ReactElement {
  return <div className="t-scroll"><table className="tbl">{children}</table></div>;
}

function MiniBars(): ReactElement {
  const months = ["ม.ค.", "ก.พ.", "มี.ค.", "เม.ย.", "พ.ค.", "มิ.ย."];
  return (
    <>
      <div className="bars">
        {[42, 55, 48, 76, 64, 88].map((v) => (
          <div key={v} className="bcol" style={{ flexDirection: "row", alignItems: "flex-end", gap: 3 }}>
            <div className="bseg in" style={{ flex: 1, height: `${v}%` }} />
            <div className="bseg ex" style={{ flex: 1, height: `${Math.max(24, v - 28)}%` }} />
          </div>
        ))}
      </div>
      <div className="bars-x">{months.map((m) => <span key={m}>{m}</span>)}</div>
    </>
  );
}

export function DesignDashboard({ goto }: { goto?: (page: PageId) => void }): ReactElement {
  return (
    <div className="content-wrap">
      <PageHead eyebrow="ภาพรวม" title="แดชบอร์ด" desc="สรุปสถานะการเงิน การบริจาค และงานที่ต้องดำเนินการ ประจำวันที่ ๔ มิถุนายน ๒๕๖๙" actions={<><Button variant="secondary">ส่งออกสรุป</Button><Button variant="primary" onClick={() => goto?.("donations")}>บันทึกการบริจาค</Button></>} />
      <div className="grid g-4" style={{ marginBottom: 16 }}>
        <KPI label="รับบริจาคเดือนนี้" value="฿96,000" tone="accent" foot="▲ 18% vs. พ.ค." />
        <KPI label="รายจ่ายเดือนนี้" value="฿60,030" tone="debit" foot="▼ 12% vs. พ.ค." />
        <KPI label="ยอดคงเหลือทุกกองทุน" value="฿1,488,000" foot="ณ วันนี้" />
        <KPI label="ผู้บริจาคใหม่เดือนนี้" value="12" foot="ราย" />
      </div>
      <div className="split-wide" style={{ marginBottom: 16 }}>
        <Card><div className="card-head"><div><h3>รายรับ-รายจ่าย ๖ เดือนล่าสุด</h3><div className="sub">เปรียบเทียบแนวโน้ม</div></div><Button variant="tertiary" size="sm" onClick={() => goto?.("reports")}>ดูรายงาน ›</Button></div><div className="card-pad"><MiniBars /></div></Card>
        <Card><div className="card-head"><h3>งานที่ต้องดำเนินการ</h3></div>{["รอออกใบอนุโมทนาบัตร", "รายการรอกระทบยอด", "คำขอจัดกิจกรรมรอตรวจสอบ"].map((t, i) => <div key={t} className="row" style={{ padding: "13px 18px", borderBottom: i < 2 ? "1px solid var(--border)" : 0 }}><span className="av">{i + 1}</span><span style={{ flex: 1 }}>{t}</span><Badge kind={i === 1 ? "reconciled" : "pending"}>1</Badge></div>)}</Card>
      </div>
      <div className="split-wide">
        <Card><div className="card-head"><div><h3>การบริจาคล่าสุด</h3><div className="sub">รายการที่บันทึกเข้าระบบ</div></div></div><Table><thead><tr><th>เลขที่</th><th>ผู้บริจาค</th><th>กองทุน</th><th className="num">จำนวน</th><th>สถานะ</th></tr></thead><tbody>{[["RC-2569-0142", "คุณวิภา รัตนากร", 5000], ["RC-2569-0141", "ครอบครัวสุขใจ", 12000], ["RC-2569-0139", "บริษัท ดีดีพัฒนา จำกัด", 50000]].map((r) => <tr key={r[0]} className="clickable"><td className="mono">{r[0]}</td><td>{r[1]}</td><td className="muted">กองทุนบูรณะอุโบสถ</td><td className="num"><span className="money credit">{money(Number(r[2]))}</span></td><td><Badge kind="credit" dot>ออกใบแล้ว</Badge></td></tr>)}</tbody></Table></Card>
        <div className="stack" style={{ gap: 16 }}><Card><div className="card-head"><h3>ความคืบหน้ากองทุน</h3></div><div className="card-pad"><div className="between"><span>กองทุนบูรณะอุโบสถ</span><span className="muted tnum">60%</span></div><div className="prog"><i style={{ width: "60%" }} /></div><div className="muted tnum" style={{ fontSize: 12, marginTop: 6 }}>฿1,200,000 / ฿2,000,000</div></div></Card><Card><div className="card-head"><h3>กิจกรรมใกล้ถึง</h3></div><div className="row" style={{ padding: "12px 18px" }}><span className="av">12</span><span>ทอดผ้าป่าสามัคคี<br/><span className="muted">09:00 · ศาลาการเปรียญ</span></span></div></Card></div>
      </div>
    </div>
  );
}

export function DesignDonations(): ReactElement {
  return <div className="content-wrap"><PageHead eyebrow="การบริจาค" title="บันทึกการบริจาค" desc="กรอกข้อมูลผู้บริจาคและจำนวนเงิน ระบบจะออกใบอนุโมทนาบัตรและบันทึกเข้าบัญชีรายรับโดยอัตโนมัติ" /><div className="split"><div><Card pad><h3 style={{ marginBottom: 14 }}>ข้อมูลผู้บริจาค</h3><div className="seg" style={{ marginBottom: 18 }}><button className="active">บุคคล</button><button>นิติบุคคล</button><button>ไม่ประสงค์ออกนาม</button></div><div className="form-grid"><label className="field full"><span className="label">ชื่อ-นามสกุล</span><input className="control" placeholder="เช่น คุณวิภา รัตนากร" /></label><label className="field"><span className="label">เบอร์โทรศัพท์</span><input className="control" placeholder="08x-xxx-xxxx" /></label><label className="field"><span className="label">อีเมล</span><input className="control" placeholder="name@example.com" /></label></div></Card><Card pad style={{ marginTop: 16 }}><h3 style={{ marginBottom: 14 }}>รายละเอียดการบริจาค</h3><label className="field"><span className="label">กองทุน / วัตถุประสงค์</span><select className="control"><option>กองทุนบูรณะอุโบสถ</option><option>กองทุนภัตตาหารพระสงฆ์</option></select></label><label className="field"><span className="label">จำนวนเงิน</span><div style={{ display: "flex", gap: 7, marginBottom: 9 }}><button className="chip">฿100</button><button className="chip active">฿500</button><button className="chip">฿1,000</button></div><div className="input-prefix"><span className="pfx">฿</span><input className="control tnum" placeholder="0" /></div></label><Button variant="primary" size="lg">บันทึกการบริจาค</Button></Card></div><Card><div className="card-head"><h3>สรุปรายการ</h3></div><div className="card-pad"><div style={{ textAlign: "center", paddingBottom: 16, borderBottom: "1px dashed var(--border-2)", marginBottom: 16 }}><div className="muted">จำนวนเงินบริจาค</div><div className="tnum" style={{ fontSize: 34, fontWeight: 600, color: "var(--accent)" }}>฿0</div></div>{[["ผู้บริจาค", "—"], ["กองทุน", "กองทุนบูรณะอุโบสถ"], ["ใบอนุโมทนา", "ออกทันที"]].map(([k, v]) => <div key={k} className="between" style={{ padding: "7px 0" }}><span className="muted">{k}</span><b>{v}</b></div>)}</div></Card></div></div>;
}

export function DesignDonors({ canWrite, goto }: { canWrite: boolean; goto?: (page: PageId) => void }): ReactElement {
  return <div className="content-wrap"><PageHead eyebrow="การบริจาค" title="ทะเบียนผู้บริจาค" desc="โปรไฟล์ผู้บริจาค ประวัติการบริจาค เอกสารที่ออก และกลุ่มผู้บริจาคสำคัญ" actions={canWrite ? <Button variant="primary">เพิ่มผู้บริจาค</Button> : undefined} /><div className="split"><div><Card pad style={{ marginBottom: 16 }}><div className="row" style={{ gap: 16, alignItems: "flex-start" }}><span className="av lg">ว</span><div style={{ flex: 1 }}><h2>คุณวิภา รัตนากร</h2><div className="mono muted">DN-0001</div><div className="row" style={{ marginTop: 10 }}><Badge kind="accent">ผู้บริจาค VIP</Badge><Badge kind="neutral">บุคคล</Badge></div></div><Button variant="primary" size="sm" onClick={() => goto?.("donations")}>บันทึกบริจาค</Button></div></Card><div className="grid g-3" style={{ marginBottom: 16 }}><KPI label="ยอดบริจาคสะสม" value="฿88,500" /><KPI label="จำนวนครั้ง" value="9 ครั้ง" /><KPI label="บริจาคล่าสุด" value="๔ มิ.ย. ๒๕๖๙" /></div><Card><div className="card-head"><h3>ประวัติการบริจาค</h3></div><Table><thead><tr><th>เลขที่ใบเสร็จ</th><th>วันที่</th><th>กองทุน</th><th className="num">จำนวน</th><th>สถานะ</th></tr></thead><tbody>{[5000, 20000, 3000].map((a, i) => <tr key={a} className="clickable"><td className="mono">RC-2569-0{142 - i}</td><td>๔ มิ.ย. ๒๕๖๙</td><td className="muted">กองทุนบูรณะอุโบสถ</td><td className="num"><span className="money credit">{money(a)}</span></td><td><Badge kind="credit" dot>ออกใบแล้ว</Badge></td></tr>)}</tbody></Table></Card></div><div className="stack" style={{ gap: 16 }}><Card><div className="card-head"><h3>ข้อมูลติดต่อ</h3></div><div className="card-pad"><dl className="dl" style={{ gridTemplateColumns: "92px 1fr" }}><dt>เบอร์โทร</dt><dd>081-234-5678</dd><dt>อีเมล</dt><dd>wipa@example.com</dd><dt>ที่อยู่</dt><dd>112/4 ถ.นิมมานเหมินท์ จ.เชียงใหม่</dd></dl></div></Card><Card><div className="card-head"><h3>เอกสารที่ออก</h3></div><div className="row" style={{ padding: "12px 18px" }}><span className="av">อ</span><span>ใบอนุโมทนา RC-2569-0142</span></div></Card></div></div></div>;
}

export function DesignReceipt(): ReactElement {
  return <div className="content-wrap"><PageHead eyebrow="การบริจาค" title="ใบอนุโมทนาบัตร" desc="ดูตัวอย่าง พิมพ์ หรือส่งใบอนุโมทนาบัตรให้ผู้บริจาค รูปแบบเอกสารทางการของวัด" actions={<><Button variant="secondary">ส่งอีเมล</Button><Button variant="primary">พิมพ์</Button></>} /><div className="split"><div className="doc"><div className="between" style={{ alignItems: "flex-start", marginBottom: 24 }}><div className="row"><div className="doc-seal">วัด</div><div><div style={{ fontSize: 19, fontWeight: 600 }}>วัดธรรมสถิตวนาราม</div><div style={{ fontSize: 12.5, color: "var(--ink-2)", fontFamily: "var(--font)" }}>๑๒๓ หมู่ ๔ ต.ในเมือง อ.เมือง จ.เชียงใหม่</div></div></div><div style={{ textAlign: "right", fontFamily: "var(--font)" }}><div className="muted">เลขที่</div><b>อ.๒๕๖๙/๐๑๔๒</b></div></div><div style={{ textAlign: "center", margin: "18px 0 24px" }}><div style={{ fontSize: 26, fontWeight: 700, color: "var(--accent)" }}>ใบอนุโมทนาบัตร</div><div className="muted">ออกให้ ณ วันที่ ๔ มิถุนายน ๒๕๖๙</div></div><div style={{ textAlign: "center", lineHeight: 2 }}>ขออนุโมทนาบุญแด่<br/><span style={{ fontSize: 22, fontWeight: 600 }}>คุณวิภา รัตนากร</span></div><div style={{ margin: "24px 0", padding: "18px 22px", background: "var(--surface-2)", border: "1px solid var(--border)", borderRadius: "var(--r)" }}><div className="between"><div><div className="muted">ได้บริจาคทรัพย์เพื่อ</div><b>กองทุนบูรณะอุโบสถ</b></div><div className="tnum" style={{ fontSize: 30, fontWeight: 700, color: "var(--accent)" }}>฿5,000</div></div></div><p style={{ textAlign: "center", lineHeight: 1.9 }}>ขออำนาจคุณพระศรีรัตนตรัยและสิ่งศักดิ์สิทธิ์ทั้งหลาย<br/>จงดลบันดาลให้ท่านและครอบครัว ประสบแต่ความสุขความเจริญ เทอญ</p></div><Card><div className="card-head"><h3>ใบที่ออกล่าสุด</h3></div>{["อ.๒๕๖๙/๐๑๔๒", "อ.๒๕๖๙/๐๑๔๑", "อ.๒๕๖๙/๐๑๓๙"].map((n) => <button key={n} className="row" style={{ width: "100%", padding: "12px 18px", border: 0, borderBottom: "1px solid var(--border)", background: "transparent", textAlign: "left" }}><span className="av">อ</span><span style={{ flex: 1 }}><b>{n}</b><br/><span className="muted">คุณวิภา รัตนากร</span></span><span className="money credit">฿5,000</span></button>)}</Card></div></div>;
}

export function DesignLedger(): ReactElement { return <div className="content-wrap"><PageHead eyebrow="การเงิน" title="บัญชีรายรับ-รายจ่าย" desc="สมุดบัญชีของวัด บันทึกและกระทบยอดรายการเงินเข้า-ออกทุกประเภท" actions={<><Button variant="secondary">ส่งออก</Button><Button variant="primary">เพิ่มรายการ</Button></>} /><div className="grid g-3" style={{ marginBottom: 16 }}><KPI label="รายรับรวม (มิ.ย.)" value="฿96,000" tone="credit" /><KPI label="รายจ่ายรวม (มิ.ย.)" value="฿60,030" tone="debit" /><KPI label="คงเหลือสุทธิ" value="฿35,970" /></div><Card><div className="t-toolbar"><div className="seg"><button className="active">ทั้งหมด</button><button>รายรับ</button><button>รายจ่าย</button></div><button className="chip active">สถานะทั้งหมด</button><button className="chip">กระทบยอดแล้ว</button><span className="muted" style={{ marginLeft: "auto" }}>4 รายการ</span></div><Table><thead><tr><th>รหัส</th><th>วันที่</th><th>หมวดบัญชี</th><th>รายละเอียด</th><th className="num">รายรับ</th><th className="num">รายจ่าย</th><th>สถานะ</th><th></th></tr></thead><tbody><tr><td className="mono">LG-0461</td><td>๔ มิ.ย. ๒๕๖๙</td><td>เงินบริจาค</td><td>บริจาคบูรณะอุโบสถ</td><td className="num"><span className="money credit">฿5,000</span></td><td className="num">—</td><td><Badge kind="pending" dot>รอตรวจสอบ</Badge></td><td className="num"><Button variant="tertiary" size="sm">กระทบยอด</Button></td></tr></tbody></Table></Card></div>; }

export function DesignEvents(): ReactElement { return <div className="content-wrap"><PageHead eyebrow="งานวัด" title="กิจกรรมและพิธี" desc="จองและจัดการกิจกรรม งานบุญ พิธีอุปสมบท ฌาปนกิจ และการปฏิบัติธรรม" actions={<Button variant="primary">จองกิจกรรม</Button>} /><div className="split"><Card><div className="t-toolbar"><div className="seg"><button className="active">ทั้งหมด</button><button>งานบุญ</button><button>อุปสมบท</button><button>ฌาปนกิจ</button></div><span className="muted" style={{ marginLeft: "auto" }}>4 กิจกรรม</span></div><Table><thead><tr><th>กิจกรรม</th><th>ประเภท</th><th>วันที่ / เวลา</th><th>สถานที่</th><th className="num">ผู้ร่วม</th><th>สถานะ</th></tr></thead><tbody><tr><td><b>ทอดผ้าป่าสามัคคี</b><div className="mono muted">EV-0236 · คุณวิภา</div></td><td><Badge kind="accent">งานบุญ</Badge></td><td>๑๒ มิ.ย. ๒๕๖๙<div className="muted">09:00–12:00</div></td><td>ศาลาการเปรียญ</td><td className="num tnum">120</td><td><Badge kind="credit" dot>ยืนยันแล้ว</Badge></td></tr></tbody></Table></Card><Card pad><h3 style={{ marginBottom: 12 }}>มิถุนายน ๒๕๖๙</h3><div style={{ display: "grid", gridTemplateColumns: "repeat(7,1fr)", gap: 3 }}>{["อา", "จ", "อ", "พ", "พฤ", "ศ", "ส", ...Array.from({ length: 30 }, (_, i) => String(i + 1))].map((d) => <div key={d} style={{ aspectRatio: "1", borderRadius: "var(--r-xs)", background: Number(d) === 12 ? "var(--accent-tint-2)" : "var(--surface-2)", padding: 4, fontSize: 12 }}>{d}</div>)}</div></Card></div></div>; }

export function DesignPeople(): ReactElement { return <div className="content-wrap"><PageHead eyebrow="งานวัด" title="พระสงฆ์และเจ้าหน้าที่" desc="ทะเบียนพระภิกษุ สามเณร และเจ้าหน้าที่ของวัด พร้อมประวัติและข้อมูลติดต่อ" actions={<Button variant="primary">เพิ่มบุคลากร</Button>} /><Card><div className="t-toolbar"><div className="seg"><button className="active">ทั้งหมด</button><button>พระ-เณร (5)</button><button>เจ้าหน้าที่ (3)</button></div></div><Table><thead><tr><th>ฉายา / ชื่อ</th><th>ประเภท</th><th>ตำแหน่ง</th><th>พรรษา</th><th>สังกัด/ติดต่อ</th><th>สถานะ</th></tr></thead><tbody>{[["พระมหาวิชัย ปญฺญาวโร", "พระภิกษุ", "เลขานุการเจ้าอาวาส", "12 พรรษา"], ["ศิริพร อินทรา", "เจ้าหน้าที่", "การเงิน", "—"]].map((p) => <tr key={String(p[0])} className="clickable"><td><div className="row"><span className="av">{String(p[0]).charAt(0)}</span><b>{p[0]}</b></div></td><td><Badge kind={p[1] === "เจ้าหน้าที่" ? "reconciled" : "accent"}>{p[1]}</Badge></td><td>{p[2]}</td><td className="tnum">{p[3]}</td><td className="muted">กุฏิ ๑</td><td><Badge kind="credit" dot>จำพรรษา</Badge></td></tr>)}</tbody></Table></Card></div>; }

export function DesignReports(): ReactElement { return <div className="content-wrap"><PageHead eyebrow="รายงาน" title="รายงานและส่งออกข้อมูล" desc="สร้างและส่งออกรายงานการเงิน การบริจาค และกิจกรรม สำหรับการตรวจสอบและจัดเก็บ" /><div className="split"><div className="grid g-2">{["รายงานการบริจาค", "งบรายรับ-รายจ่าย", "รายงานผู้บริจาค", "รายงานเพื่อลดหย่อนภาษี", "รายงานกิจกรรม", "รายงานความคืบหน้ากองทุน"].map((r, i) => <button key={r} className="card" style={{ textAlign: "left", padding: 18, borderColor: i === 0 ? "var(--accent)" : "var(--border)", background: i === 0 ? "var(--accent-tint-2)" : "var(--surface)" }}><span className="av">ร</span><div style={{ fontWeight: 600, marginTop: 11 }}>{r}</div><div className="muted" style={{ fontSize: 12.5 }}>สรุปข้อมูลและส่งออก</div></button>)}</div><Card><div className="card-head"><h3>ตั้งค่ารายงาน</h3></div><div className="card-pad"><label className="field"><span className="label">ช่วงเวลา</span><input className="control tnum" value="2569-05-01 ถึง 2569-06-04" readOnly /></label><label className="opt sel"><input type="radio" checked readOnly /><span><span className="o-title">PDF</span><span className="o-desc">เหมาะสำหรับพิมพ์และจัดเก็บ</span></span></label><label className="opt"><input type="radio" readOnly /><span><span className="o-title">Excel (.xlsx)</span><span className="o-desc">เปิดแก้ไขและคำนวณต่อได้</span></span></label><Button variant="primary" className="btn-block">สร้างและดาวน์โหลด</Button></div></Card></div></div>; }

export function DesignRoles({ role }: { role: TempleRole }): ReactElement { return <div className="content-wrap"><PageHead eyebrow="ระบบ" title="สิทธิ์ผู้ใช้งาน" desc="จัดการบัญชีผู้ใช้ของวัด กำหนดบทบาทและระดับสิทธิ์การเข้าถึงแต่ละส่วนของระบบ" actions={role === "admin" ? <Button variant="primary">เพิ่มบัญชีผู้ใช้</Button> : undefined} /><div className="seg" style={{ marginBottom: 16 }}><button className="active">บัญชีผู้ใช้งาน</button><button>บทบาทและสิทธิ์</button></div><div className="grid g-4" style={{ marginBottom: 16 }}><KPI label="บัญชีทั้งหมด" value="7" /><KPI label="ใช้งานอยู่" value="6" tone="credit" /><KPI label="ปิดใช้งาน" value="1" tone="void" /><KPI label="ผู้ดูแลระบบ" value="2" /></div><Card><div className="card-head"><div><h3>บทบาทและสิทธิ์</h3><div className="sub">ตารางสิทธิ์การเข้าถึง</div></div></div><Table><thead><tr><th>ชื่อ-นามสกุล</th><th>อีเมล</th><th>บทบาท</th><th>เข้าระบบล่าสุด</th><th>สถานะ</th></tr></thead><tbody><tr><td><div className="row"><span className="av">ป</span><b>ประยูร พงษ์ศักดิ์</b></div></td><td className="muted">prayoon@wat.local</td><td><Badge kind="accent" dot>ผู้ดูแลวัด</Badge></td><td className="muted">วันนี้ 08:45</td><td><Badge kind="credit" dot>ใช้งาน</Badge></td></tr></tbody></Table><div className="t-foot"><span>แสดง 7 จาก 7 บัญชี</span><span>ปิดใช้งานแทนการลบ เพื่อรักษาประวัติการทำรายการ</span></div></Card></div>; }

export function DesignAudit(): ReactElement { return <div className="content-wrap"><PageHead eyebrow="ระบบ" title="บันทึกการใช้งาน" desc="บันทึกทุกการกระทำสำคัญในระบบ — ใครทำอะไร เมื่อไร เพื่อการตรวจสอบและความโปร่งใส ข้อมูลนี้ลบไม่ได้" actions={<Button variant="secondary">ส่งออกบันทึก</Button>} /><Card><div className="t-toolbar"><button className="chip active">ทั้งหมด</button><button className="chip">สร้าง</button><button className="chip">แก้ไข</button><button className="chip">ลบ/ยกเลิก</button><span className="muted" style={{ marginLeft: "auto" }}>4 รายการ</span></div><Table><thead><tr><th>เวลา</th><th>ผู้ใช้งาน</th><th>การกระทำ</th><th>รายการ / รายละเอียด</th><th>IP</th></tr></thead><tbody><tr><td className="mono">2569-06-04 09:12</td><td><div className="row"><span className="av">ป</span><span>ประยูร พงษ์ศักดิ์<br/><span className="muted">admin</span></span></div></td><td><Badge kind="credit" dot>สร้าง</Badge></td><td><b>RC-2569-0142</b><div className="muted">บันทึกการบริจาคและออกใบอนุโมทนา</div></td><td className="mono muted">127.0.0.1</td></tr></tbody></Table><div className="t-foot"><span>แสดง 4 จาก 4 รายการ</span><span>บันทึกนี้ไม่สามารถแก้ไขหรือลบได้</span></div></Card></div>; }

export function DesignSystemShowcase(): ReactElement { return <div className="content-wrap"><PageHead eyebrow="ระบบ" title="ระบบออกแบบ" desc="คอมโพเนนต์พื้นฐานที่ port จาก design artifact: btn btn-primary, badge, card, table, form" /><Card pad><div className="row" style={{ flexWrap: "wrap" }}><button className="btn btn-primary">btn btn-primary</button><button className="btn btn-secondary">btn btn-secondary</button><button className="btn btn-tertiary">btn btn-tertiary</button><Badge kind="credit" dot>รายรับ</Badge><Badge kind="pending" dot>รอตรวจสอบ</Badge></div></Card></div>; }
